# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TLMonthYearPickerExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'TLMonthYearPicker', :path => '../'
  #pod 'TLMonthYearPicker', :git => 'https://github.com/lee5783/TLMonthYearPicker.git'
  #pod 'TLMonthYearPicker'
end
